name: intrezo_jobs
description: "Job search app for foreign workers in Estonia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  file_picker: ^10.2.0
  firebase_storage: ^11.5.6
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/headerLogo.png
    - assets/images/baker.png
    - assets/images/taxi.png
    - assets/images/assistant.png
    - assets/images/team_photo.png
    - assets/images/mission_image.png
    - assets/images/vision_image.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-Italic.ttf
          style: italic