name: intrezo_jobs
description: "Job search app for foreign workers in Estonia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/headerLogo.png
    - assets/images/baker.png
    - assets/images/taxi.png
    - assets/images/assistant.png